- name: Add the user {{ user }}
  ansible.builtin.user:
    name: "{{ user }}"

- name: Install requirements
  apt:
    name:
      - curl
      - git
      - snapd
      - speedcrunch
      - redis-server
      - php-redis
    update_cache: yes

- name: Download and install Composer
  shell: curl -sS https://getcomposer.org/installer | php
  args:
    chdir: /usr/src/
    creates: /usr/local/bin/composer
    warn: false

- name: Add Composer to global path
  copy:
    dest: /usr/local/bin/composer
    group: root
    mode: "0755"
    owner: root
    src: /usr/src/composer.phar
    remote_src: yes

- name: Install the gpg key for nodejs LTS
  apt_key:
    url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
    state: present
- name: Add nodejs {{ node_version }}.x ppa for apt repo
  apt_repository:
    repo: deb https://deb.nodesource.com/node_{{ node_version }}.x focal main
    update_cache: yes
- name: "Install nodejs"
  apt:
    update_cache: yes
    name: nodejs
    state: present

- name: Install Code
  community.general.snap:
    name: code
    classic: yes

- name: Install postman
  community.general.snap:
    name: postman
    classic: yes

- name: Install Telegram
  community.general.snap:
    name: telegram-desktop
    classic: yes

- name: Install Laravel via composer
  shell: composer global require laravel/installer

- name: Install Quasar via npm
  shell: npm install -g @quasar/cli
