- name: Install PHPStorm
  community.general.snap:
    name: phpstorm
    classic: yes

- name: Install Webstom
  community.general.snap:
    name: webstorm
    classic: yes

- name: "Jetbrains Toolbox"
  block:
    - name: "Download {{ application_name }} of version {{ toolbox_version }}"
      get_url:
        url: "{{ download_url }}"
        dest: "{{ temporary_file_name }}"

    - name: "Install to {{ toolbox_install_dir }}"
      unarchive:
        remote_src: true
        src: "{{ temporary_file_name }}"
        dest: "{{ toolbox_install_dir }}"

    - name: "Move executable from the folder"
      copy:
        src: "{{ toolbox_install_dir }}/{{ toolbox_install_file }}-{{ toolbox_version }}/{{ toolbox_install_file }}"
        dest: "{{ toolbox_install_path }}"
        remote_src: true
        owner: "root"
        group: "root"
        mode: "0777"

    - name: "Remove temporary folders and files"
      file:
        name: "{{ item }}"
        state: "absent"
      with_items:
        - "{{ toolbox_install_dir }}/{{ toolbox_install_file }}-{{ toolbox_version }}"
        - "{{ temporary_file_name }}"

    - name: "Run as user to finish installation"
      command: "{{ toolbox_install_path }}"
      become: true
      become_user: "{{ toolbox_install_for_user }}"
      when: toolbox_install_for_user | length

    - name: Reminder how to launch
      debug:
        msg: |
          User, who will use {{ application_name }}, have to run {{ toolbox_install_path }}
          manually for the first time.
      when: not( toolbox_install_for_user | length )

  when: is_installed.matched == 0

- name: Set Inotify Watches Limit
  sysctl: name="fs.inotify.max_user_watches"
    value="{{ inotify_max_user_watches }}"
    state="present"
    reload="yes"
