- name: Installation PHP 7.4
  apt: name=php7.4 state=present

- name: Install packages
  apt:
    pkg:
      - php7.4-mysql
      - php7.4-curl
      - php7.4-json
      - php7.4-cgi
      - php7.4-xsl
      - php7.4-cgi
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-zip
      - php7.4-xmlrpc
      - php7.4-soap
      - php7.4-intl
      - php-imagick
      - libapache2-mod-php
    state: present
    update_cache: yes
